[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x --protocol swd --catch-hardfault --always-print-stacktrace" # for jtag
# runner = "elf2uf2-rs --deploy --serial --verbose" # for elf2uf2
linker = "flip-link"

[build]
target = "thumbv8m.main-none-eabihf"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
