[package]
name = "epd-frame-rs-2-common"
version = "0.1.0"
edition = "2024"

[features]
default = ["defmt"]
defmt = ["defmt-or-log/defmt", "embassy-net/defmt", "sntpc/defmt", "sntpc-net-embassy/defmt",
    "chrono/defmt", "embedded-graphics/defmt", "embedded-hal/defmt-03", "embedded-hal-async/defmt-03",
    "mplusfonts/defmt", "picoserve/defmt", "embassy-sync/defmt", "embassy-futures/defmt"]
log = ["defmt-or-log/log", "sntpc/log", "sntpc-net-embassy/log", "dep:log", "reqwless/log", "picoserve/log",
    "embassy-sync/log", "embassy-futures/log"]
std = ["picoserve/std", "embassy-sync/std"]

[dependencies]
defmt = { workspace = true }
log = { workspace = true, features = ["max_level_info"], optional = true }
defmt-or-log = { workspace = true }
zerocopy = { workspace = true }
static_cell = { workspace = true }
thiserror = { workspace = true }
embassy-net = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
embassy-sync = { version = "0.8.0" }
embassy-futures = { workspace = true }

# Fix for embedded-tls shit
#der = { version = "0.8.0-rc.2", features = ["derive", "oid", "time", "heapless"] }
#rsa = { version = "0.9.9", features = ["sha2"], default-features = false }
#embedded-tls = { version = "0.18.0", features = ["rustpki", "log"], default-features = false }

sntpc = { version = "0.8.0", default-features = false }
sntpc-net-embassy = { version = "0.8.0", features = ["ipv6"], default-features = false }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

embedded-graphics = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-layout = { git = "https://github.com/bugadani/embedded-layout" }

mplusfonts = { version = "0.3.4", default-features = false }
mplusfonts-macros = { version = "0.3.4", default-features = false }
micromath = { version = "2.1.0", default-features = false }
fastrand = { version = "2.4.1", features = ["alloc"], default-features = false }
qrcodegen-no-heap = { version = "1.8.1" }

reqwless = { workspace = true }
picoserve = { version = "0.18.0", features = ["embassy", "alloc"], default-features = false }
maud = { version = "0.27.0" }